server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Статика (Vue)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Proxy
    # Запит браузера: /api/v1/tasks
    # Йде на: http://backend-svc:80/api/v1/tasks
    location /api/ {
        proxy_pass http://backend-svc.todo-app.svc.cluster.local:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}