apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: todo-frontend:v1 # Наш образ, який ми щойно зібрали
        imagePullPolicy: Never    # Брати з Minikube
        ports:
        - containerPort: 80