apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: todo-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # На цей порт ми будемо стукати
      targetPort: 80  # Це порт Nginx всередині